src/Entity/Seance.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Seance
 *
 * @ORM\Table(name="seance", indexes={@ORM\Index(name="test", columns={"id_matiere"}), @ORM\Index(name="test123", columns={"id_professeur"})})
 * @ORM\Entity(repositoryClass="App\Repository\SeanceRepository")
 */
class Seance
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_seance", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idSeance;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dtdebut", type="date", nullable=false)
     */
    private $dtdebut;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dtfin", type="date", nullable=false)
     */
    private $dtfin;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="h_debut", type="time", nullable=false)
     */
    private $hDebut;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="h_fin", type="time", nullable=false)
     */
    private $hFin;

    /**
     * @var int
     *
     * @ORM\Column(name="salle", type="integer", nullable=false)
     */
    private $salle;

    /**
     * @var bool
     *
     * @ORM\Column(name="effectuer", type="boolean", nullable=false)
     */
    private $effectuer;

    /**
     * @var \Matiere
     *
     * @ORM\ManyToOne(targetEntity="Matiere")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_matiere", referencedColumnName="id_matiere")
     * })
     */
    private $idMatiere;

    /**
     * @var \Professeur
     *
     * @ORM\ManyToOne(targetEntity="Professeur")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_professeur", referencedColumnName="id")
     * })
     */
    private $idProfesseur;

    /**
     * @ORM\Column(type="date")
     */
    private $Jour;

    public function getIdSeance(): ?int
    {
        return $this->idSeance;
    }

    public function getDtdebut(): ?\DateTimeInterface
    {
        return $this->dtdebut;
    }

    public function setDtdebut(\DateTimeInterface $dtdebut): self
    {
        $this->dtdebut = $dtdebut;

        return $this;
    }

    public function getDtfin(): ?\DateTimeInterface
    {
        return $this->dtfin;
    }

    public function setDtfin(\DateTimeInterface $dtfin): self
    {
        $this->dtfin = $dtfin;

        return $this;
    }


    public function getHDebut(): ?\DateTimeInterface
    {
        return $this->hDebut;
    }

    public function setHDebut(\DateTimeInterface $hDebut): self
    {
        $this->hDebut = $hDebut;

        return $this;
    }

    public function getHFin(): ?\DateTimeInterface
    {
        return $this->hFin;
    }

    public function setHFin(\DateTimeInterface $hFin): self
    {
        $this->hFin = $hFin;

        return $this;
    }

    public function getSalle(): ?int
    {
        return $this->salle;
    }

    public function setSalle(int $salle): self
    {
        $this->salle = $salle;

        return $this;
    }

    public function getEffectuer(): ?bool
    {
        return $this->effectuer;
    }

    public function setEffectuer(bool $effectuer): self
    {
        $this->effectuer = $effectuer;

        return $this;
    }

    public function getIdMatiere(): ?Matiere
    {
        return $this->idMatiere;
    }

    public function setIdMatiere(?Matiere $idMatiere): self
    {
        $this->idMatiere = $idMatiere;

        return $this;
    }

    public function getIdProfesseur(): ?Professeur
    {
        return $this->idProfesseur;
    }

    public function setIdProfesseur(?Professeur $idProfesseur): self
    {
        $this->idProfesseur = $idProfesseur;

        return $this;
    }

    public function getJour(): ?\DateTimeInterface
    {
        return $this->Jour;
    }

    public function setJour(\DateTimeInterface $Jour): self
    {
        $this->Jour = $Jour;

        return $this;
    }


}

src/Form/SeanceType.php
<?php

namespace App\Form;

use App\Entity\Seance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class SeanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dtdebut', DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd'
            ])
            ->add('dtfin', DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd'
            ])
            ->add('jourdelasemaine',  ChoiceType::class, array(
                'mapped'=>false,
                'choices' => array(
                    'dimanche'=>'Sunday',
                    'lundi'=>'Monday',
                    'mardi'=>'Tuesday',
                    'mercredi'=>'Wednesday' ,
                    'jeudi'=>'Thursday',
                    'vendredi'=>'Friday',
                    'samedi'=>'Saturday'
                    ),
                 'multiple' => true, 'expanded' => true
            ))
            ->add('hDebut')
            ->add('hFin')
            ->add('salle')
            ->add('effectuer')
            ->add('idMatiere')
            ->add('idProfesseur')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Seance::class,
        ]);
    }
}

src/Controller/SeanceController.php
<?php

namespace App\Controller;
use App\Entity\Seance;
use App\Form\SeanceType;
use App\Entity\Notification;
use App\Repository\SeanceRepository;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_ADMIN")
 * @Route("/seance")
 */
class SeanceController extends AbstractController
{
    /**
     * @Route("/", name="seance_index", methods={"GET"})
     * @param SeanceRepository $seanceRepository
     * @return Response
     */
    public function index(SeanceRepository $seanceRepository): Response
    {
        return $this->render('seance/index.html.twig', [
            'seances' => $seanceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/calendar", name="seance_calendar", methods={"GET"})
     * @param SeanceRepository $seance
     * @return Response
     */
    public function calendar(SeanceRepository $seance): Response
    {
        $events=$seance->findAll();
        $rdvs=[];
        foreach ($events as $event){
            $rdvs[]=[
                'id'=>$event->getIdSeance(),
                'title'=>$event->getSalle().' '.$event->getIdMatiere().' '.$event->getIdProfesseur(),
                'start'=>$event->getJour()->format('Y-m-d').' '.$event->getHDebut()->format('H:i:s'),
                'end'=>$event->getJour()->format('Y-m-d').' '.$event->getHFin()->format('H:i:s'),
                'description'=>$event->getEffectuer(),
            ];
        }
        $data=json_encode($rdvs);
        return $this->render('seance/calendar.html.twig',compact('data'));
    }

    /**
     * @Route("/new", name="seance_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $seance = new Seance();
        $form = $this->createForm(SeanceType::class, $seance);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $jourdelasemaine=$form['jourdelasemaine']->getData();
            $dtdebut=$form['dtdebut']->getData();
            $dtfin=$form['dtfin']->getData();
            $dtdebut=strtotime($dtdebut->format("Y-m-d"));
            $dtfin=$dtfin->getTimestamp();
            $j=count($jourdelasemaine);
            $a=[];
            while($dtdebut<$dtfin){
                for($i=0;$i<$j;$i++){
                    if($jourdelasemaine[$i] == date('l',$dtdebut)){
                        array_push($a,date('Y-m-d',$dtdebut) );
                    }
                }
                $dtdebut=strtotime("+1 day",$dtdebut);
            }
            $k=count($a);
            $entityManager = $this->getDoctrine()->getManager();
            for($i=0;$i<$k;$i++){

                $group = new Seance();
                $group->setJour(DateTime::createFromFormat('Y-m-d', $a[$i]));
                $group->setIdProfesseur($form['idProfesseur']->getData());
                $group->setIdMatiere($form['idMatiere']->getData());
                $group->setHDebut($form['hDebut']->getData());
                $group->setHFin($form['hFin']->getData());
                $group->setEffectuer($form['effectuer']->getData());
                $group->setSalle($form['salle']->getData());
                $group->setDtdebut($form['dtdebut']->getData());
                $group->setDtfin($form['dtfin']->getData());
                $entityManager->persist($group);
            }
            $entityManager->flush();
            $notification = new Notification();
            $entityManager1 = $this->getDoctrine()->getManager();
            $notification->setDate(new \DateTime('now'));
            $notification->setType("new");
            $notification->setSujet("un ensemble de seances a ete ajoute ");
            $notification->setLu(FALSE);
            $entityManager1->persist($notification);
            $entityManager1->flush();

            return $this->redirectToRoute('seance_index');
        }

        return $this->render('seance/new.html.twig', [
            'seance' => $seance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idSeance}", name="seance_show", methods={"GET"})
     * @param Seance $seance
     * @return Response
     */
    public function show(Seance $seance): Response
    {
        return $this->render('seance/show.html.twig', [
            'seance' => $seance,
        ]);
    }

    /**
     * @Route("/{idSeance}/edit", name="seance_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Seance $seance
     * @return Response
     */
    public function edit(Request $request, Seance $seance): Response
    {
        $form = $this->createForm(SeanceType::class, $seance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $entityManager1 = $this->getDoctrine()->getManager();
            $notification->setDate(new \DateTime('now'));
            $notification->setSujet("modification d une seance");
            $notification->setLu(FALSE);
            $notification->setType("edit");
            $entityManager1->persist($notification);
            $entityManager1->flush();
            return $this->redirectToRoute('seance_index');
        }

        return $this->render('seance/edit.html.twig', [
            'seance' => $seance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idSeance}", name="seance_delete", methods={"DELETE"})
     * @param Request $request
     * @param Seance $seance
     * @return Response
     */
    public function delete(Request $request, Seance $seance): Response
    {
        if ($this->isCsrfTokenValid('delete'.$seance->getIdSeance(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($seance);
            $entityManager->flush();
            $entityManager1 = $this->getDoctrine()->getManager();
            $notification->setDate(new \DateTime('now'));
            $notification->setSujet("suppression d une seance");
            $notification->setLu(FALSE);
            $notification->setType("delete");
            $entityManager1->persist($notification);
            $entityManager1->flush();
        }

        return $this->redirectToRoute('seance_index');
    }
}

templates/seance/_delete_form.html.twig
<form method="post" action="{{ path('seance_delete', {'idSeance': seance.idSeance}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ seance.idSeance) }}">
    <button class="btn">Delete</button>
</form>

templates/seance/calendar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ parent() }}
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Input</h2>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Form Elements</a>
                                </li>
                                <li class="breadcrumb-item active">Input
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrum-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">

     <button id="addRow" class="btn btn-primary mb-2 waves-effect waves-light"><i class="feather icon-plus"></i>&nbsp;<a href="{{ path('seance_new') }}">Create new</a></button>
                        
    <div id="calendar-holder"></div>
        </div>

    </div>

</div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css">
{% endblock %}

{% block javascripts %}
    {{  parent() }}

    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>

    <script >
        window.onload= () => {
            let calendarEl = document.getElementById('calendar-holder');

            let calendar = new FullCalendar.Calendar(calendarEl, {
                defaultView: 'dayGridMonth',
                locale:'fr',
                events :  {{ data|raw }},
                eventColor: '#f20202',
                eventTextColor:'#000000',
                editable: true,
                eventResizableFromStart:true,
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay',
                },
                plugins: [ 'interaction', 'dayGrid', 'timeGrid' ],
                timeZone: 'UTC',
            });

             calendar.on('eventChange',(e) => {
                 console.log(e);
            });
            calendar.render();
        };
    </script>
    <script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>

    <script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
    <script src="{{ asset('app-assets/js/core/app.js') }}"></script>
    <script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
{% endblock %}

templates/seance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Seance{% endblock %}

{% block body %}
    {{ parent() }}
<div class="app-content content">
<div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Modifier une affectation :</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{ path('seance_index') }}">Seance</a>
                                    </li>
                                    <li class="breadcrumb-item active">Editer
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrum-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Inputs start -->
                <section id="basic-input">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Ajouter</h4>
                                </div>
                                <div class="card-content">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">

    {{ include('seance/_form.html.twig', {'button_label': 'Update'}) }}
    
 </fieldset>
                                            </div>
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                  
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Inputs end -->




    
    </div>
   
    
 </fieldset>
                                            </div>
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">
                                                 
   
    <a href="{{ path('seance_index') }}">back to list</a>

    {{ include('seance/_delete_form.html.twig') }}
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                  
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Inputs end -->

    </div>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
{% endblock %}



    

templates/seance/index.html.twig
                                {% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
{{ parent() }}
<div class="app-content content">
   <div class="content-overlay"></div>
   <div class="header-navbar-shadow"></div>
   <div class="content-wrapper">
      <div class="content-header row">
         <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
               <div class="col-12">
                  <h2 class="content-header-title float-left mb-0">Liste des Seances :</h2>
                  <div class="breadcrumb-wrapper col-12">
                     <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a>
                        </li>
                        <li class="breadcrumb-item"><a href="{{ path('seance_index') }}">Seance</a>
                        </li>
                        <li class="breadcrumb-item active">Liste
                        </li>
                     </ol>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <section id="basic-datatable">
         <div class="row">
            <div class="col-12">
               <div class="card">
                  <div class="card-header">
                     <h4 class="card-title">Liste des Seances</h4>
                  </div>
                  <div class="card-content">
                     <div class="card-body card-dashboard">
                        <button id="addRow" class="btn btn-primary mb-2 waves-effect waves-light"><i class="feather icon-plus"></i>&nbsp;<a href="{{ path('seance_new') }}">Create new</a></button>
                        
                        <div class="table-responsive">
                           <table class="table zero-configuration">
                              <thead>
                                 <tr>
                                 
                <th>IdSeance</th>
                <th>Jour</th>
                <th>HDebut</th>
                <th>HFin</th>
                <th>Salle</th>
                <th>Effectuer</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for seance in seances %}
            <tr>
                <td>{{ seance.idSeance }}</td>
                <td>{{ seance.jour ? seance.jour|date('Y-m-d') : '' }}</td>
                <td>{{ seance.hDebut ? seance.hDebut|date('H:i:s') : '' }}</td>
                <td>{{ seance.hFin ? seance.hFin|date('H:i:s') : '' }}</td>
                <td>{{ seance.salle }}</td>
                <td>{{ seance.effectuer ? 'Yes' : 'No' }}</td>
                <td>
                    <a class="btn btn-icon btn-outline-primary mr-1 mb-1 waves-effect waves-light" href="{{ path('seance_show', {'idSeance': seance.idSeance}) }}"><i class="feather icon-search"></i></a>
                    <a class="btn btn-icon btn-outline-primary mr-1 mb-1 waves-effect waves-light" href="{{ path('seance_edit', {'idSeance': seance.idSeance}) }}"><i class="feather icon-edit"></i></a>
                
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
         <tfoot>
                                 <tr>
                <th>IdSeance</th>
                <th>Jour</th>
                <th>HDebut</th>
                <th>HFin</th>
                <th>Salle</th>
                <th>Effectuer</th>
                <th>actions</th>
                                 </tr>
                              </tfoot>
                           </table>
                           
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   </div>
</div>
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/vfs_fonts.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/datatables/datatable.js') }}"></script>
{% endblock %}

templates/seance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seance{% endblock %}

{% block body %}
    <h1>Seance</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdSeance</th>
                <td>{{ seance.idSeance }}</td>
            </tr>
            <tr>
                <th>Jour</th>
                <td>{{ seance.jour ? seance.jour|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>HDebut</th>
                <td>{{ seance.hDebut ? seance.hDebut|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>HFin</th>
                <td>{{ seance.hFin ? seance.hFin|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Salle</th>
                <td>{{ seance.salle }}</td>
            </tr>
            <tr>
                <th>Effectuer</th>
                <td>{{ seance.effectuer ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('seance_index') }}">back to list</a>

    <a href="{{ path('seance_edit', {'idSeance': seance.idSeance}) }}">edit</a>

    {{ include('seance/_delete_form.html.twig') }}
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
    <script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
{% endblock %}