src/Entity/Niveau.php
<?php

namespace App\Entity;

use App\Repository\NiveauRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NiveauRepository::class)
 */
class Niveau
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_niveau;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNomNiveau(): ?string
    {
        return $this->nom_niveau;
    }

    public function setNomNiveau(string $nom_niveau): self
    {
        $this->nom_niveau = $nom_niveau;

        return $this;
    }
    public function __toString()
    {
        return $this->getNomNiveau();
    }

}

src/Form/NiveauType.php
<?php

namespace App\Form;

use App\Entity\Niveau;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NiveauType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('type',ChoiceType::class, [
            'placeholder'=>"",
            'mapped'=>false,
            'choices' => [
                'eleve'=> 'eleve',
                'etudiant' => 'etudiant'
            ]])
            ->add('nom_niveau')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Niveau::class,
        ]);
    }
}

src/Controller/NiveauController.php
<?php

namespace App\Controller;

use App\Entity\Niveau;
use App\Form\NiveauType;
use App\Repository\NiveauRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/niveau")
 */
class NiveauController extends AbstractController
{
    /**
     * @Route("/", name="niveau_index", methods={"GET"})
     */
    public function index(NiveauRepository $niveauRepository): Response
    {
        return $this->render('niveau/index.html.twig', [
            'niveaux' => $niveauRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="niveau_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $niveau = new Niveau();
        $form = $this->createForm(NiveauType::class, $niveau);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
                $niveau->setNomNiveau($form['nom_niveau']->getData());
            $niveau->setType($form['type']->getData());
            $entityManager->persist($niveau);
            $entityManager->flush();

            return $this->redirectToRoute('niveau_index');
        }

        return $this->render('niveau/new.html.twig', [
            'niveau' => $niveau,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="niveau_show", methods={"GET"})
     */
    public function show(Niveau $niveau): Response
    {
        return $this->render('niveau/show.html.twig', [
            'niveau' => $niveau,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="niveau_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Niveau $niveau): Response
    {
        $form = $this->createForm(NiveauType::class, $niveau);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('niveau_index');
        }

        return $this->render('niveau/edit.html.twig', [
            'niveau' => $niveau,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="niveau_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Niveau $niveau): Response
    {
        if ($this->isCsrfTokenValid('delete'.$niveau->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($niveau);
            $entityManager->flush();
        }

        return $this->redirectToRoute('niveau_index');
    }
}

templates/niveau/_delete_form.html.twig
<form method="post" action="{{ path('niveau_delete', {'id': niveau.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ niveau.id) }}">
    <button class="btn">Delete</button>
</form>

templates/niveau/_form.html.twig
{{ form_start(form) }}
{{ form_label(form.type, 'Type', {'label_attr': {'class': 'col-sm-6 '}}) }}
    {{ form_widget(form.type) }}
     <div id="test1">
    {{ form_label(form.nom_niveau,'nouveau Niveau', {'label_attr': {'class': 'col-sm-6 '}}) }}
    {{ form_widget(form.nom_niveau) }}
    </div>
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/niveau/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Niveau{% endblock %}

{% block body %}
    <h1>Edit Niveau</h1>

    {{ include('niveau/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('niveau_index') }}">back to list</a>

    {{ include('niveau/_delete_form.html.twig') }}
{% endblock %}

templates/niveau/index.html.twig
{% extends 'base.html.twig' %}

 {% block head %}
  {{ parent() }}
            <title>{% block title %}Niveau index{% endblock %}</title>
        {% endblock %}

{% block body %}
{{ parent() }}
<div class="app-content content">
   <div class="content-overlay"></div>
   <div class="header-navbar-shadow"></div>
   <div class="content-wrapper">
      <div class="content-header row">
         <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
               <div class="col-12">
                  <h2 class="content-header-title float-left mb-0">Liste des Niveau :</h2>
                  <div class="breadcrumb-wrapper col-12">
                     <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a>
                        </li>
                        <li class="breadcrumb-item"><a href="{{ path('niveau_index') }}">Niveau</a>
                        </li>
                        <li class="breadcrumb-item active">Liste
                        </li>
                     </ol>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <section id="basic-datatable">
         <div class="row">
            <div class="col-12">
               <div class="card">
                  <div class="card-header">
                     <h4 class="card-title">Liste des Niveaux</h4>
                  </div>
                  <div class="card-content">
                     <div class="card-body card-dashboard">
                        <button id="addRow" class="btn btn-primary mb-2 waves-effect waves-light"><i class="feather icon-plus"></i>&nbsp;<a href="{{ path('niveau_new') }}">Create new</a></button>
                        <div class="table-responsive">
                           <table class="table zero-configuration">
                              <thead>
                                 <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Nom niveau</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for niveau in niveaux %}
            <tr>
                <td>{{ niveau.id }}</td>
                <td>{{ niveau.type }}</td>
                <td>{{ niveau.nomNiveau }}</td>
                <td>
                 <a class="btn btn-icon btn-outline-primary mr-1 mb-1 waves-effect waves-light" href="{{ path('niveau_show', {'id': niveau.id}) }}"><i class="feather icon-search"></i></a>
                    <a class="btn btn-icon btn-outline-primary mr-1 mb-1 waves-effect waves-light" href="{{ path('niveau_edit', {'id': niveau.id}) }}"><i class="feather icon-edit"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
                              <tfoot>
                                 <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Nom niveau</th>
                <th>actions</th>
                                 </tr>
                              </tfoot>
                           </table>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   </div>
</div>
</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/vfs_fonts.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('/app-assets/vendors/js/forms/select/select2.full.min.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/datatables/datatable.js') }}"></script>
{% endblock %}

templates/niveau/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Seance{% endblock %}

{% block body %}
    {{ parent() }}

<div class="app-content content">
<div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Créer une Niveau :</h2>
                            <div class="breadcrumb-wrapper col-12">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Accueil</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{ path('niveau_index') }}">Niveau</a>
                                    </li>
                                    <li class="breadcrumb-item active">Nouveau
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrum-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Inputs start -->
                <section id="basic-input">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Ajouter</h4>
                                </div>
                                <div class="card-content">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">


    {{ include('niveau/_form.html.twig') }}
 
 </fieldset>
                                            </div>
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                  
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Inputs end -->




    
    </div>
   
    
 </fieldset>
                                            </div>
                                            <div class="col-xl-4 col-sm-6 col-12 mb-1">
                                                <fieldset class="form-group">
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                  
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Inputs end -->



<a href="{{ path('niveau_index') }}">back to list</a>
    
    </div>

{% endblock %}
{% block javascripts %}
{{ parent() }}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/components.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/forms/select/form-select2.js') }}"></script>
{% endblock %}

templates/niveau/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Niveau{% endblock %}

{% block body %}
    <h1>Niveau</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ niveau.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ niveau.type }}</td>
            </tr>
            <tr>
                <th>Nom_niveau</th>
                <td>{{ niveau.nomNiveau }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('niveau_index') }}">back to list</a>

    <a href="{{ path('niveau_edit', {'id': niveau.id}) }}">edit</a>

    {{ include('niveau/_delete_form.html.twig') }}
{% endblock %}